version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Directory containing Dockerfile
      dockerfile: Dockerfile
    container_name: backend
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"    # MQTT port
      - "9001:9001"    # WebSocket port (optional)
    volumes:
      - ./containers_data/mosquitto/data:/mosquitto/data
      - ./containers_data/mosquitto/config:/mosquitto/config
      - ./containers_data/mosquitto/log:/mosquitto/log
    restart: unless-stopped
