version: '3.8'

services:
  backend_db:
    build:
      context: ./backend_db  # Directory containing Dockerfile
      dockerfile: Dockerfile
    container_name: backend_db
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend_db:/app
    ports:
      - "8000:8000"
    networks:
      - zigbee_network

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"    # MQTT port
      - "9001:9001"    # WebSocket port (optional)
    volumes:
      - ./containers_data/mosquitto/data:/mosquitto/data
      - ./containers_data/mosquitto/config:/mosquitto/config
      - ./containers_data/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    depends_on:
      - backend_db
    networks:
      - zigbee_network

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    ports:
      - "8080:8080"  
    volumes:
      - ./containers_data/zigbee2mqtt/config:/app/data
    devices:
      - "/dev/ttyACM2:/dev/ttyACM2"  
    environment:
      - TZ=Europe/Berlin  # Adjust the timezone if needed
      - MQTT_SERVER=mqtt://mqtt:1883
    depends_on:
      - mqtt
    networks:
      - zigbee_network
      
  backend_hub:
    build:
      context: ./backend_hub  # Directory containing Dockerfile
      dockerfile: Dockerfile
    container_name: backend_hub
    volumes:
      - ./backend_hub:/app
    depends_on:
      - mqtt
      - backend_db
    networks:
      - zigbee_network
    profiles:
      - manual-start

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend_db
    networks:
      - zigbee_network

networks:
  zigbee_network:
    driver: bridge