serial:
  adapter: ember
  port: /dev/ttyACM2
  rtscts: false
external_converters:
  - converter.js
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1883
frontend:
  port: 8080
logger:
  level: debug
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xf082c0fffe81c65a':
    friendly_name: Stikalo-Ikea
  '0xf4ce3620277fadba':
    friendly_name: '0xf4ce3620277fadba'
